### ISSUE TITLE
Data discrepancies on Web Weather Dashboard

### ISSUE THREAD

**Issue by vinpcat** [charliemaxh/Web-Weather-Dashboard#14]

**Comment by vinpcat** [comment]
There are some issues with the data on the dashboard, specifically with time and date.

We've identified that the issue may be due to some naming conventions as other locations have similar names eg. Perth - Australia and Perth Canada. 

![Image](https://github.com/user-attachments/assets/4189be1c-0e2e-4957-9c09-fbe2b660270f)

**Comment by charliemaxh** [comment]
i think some code could be added to either force the user to specify a country code (Eg AU) or to include a list if there is multiple Sydneys (there are 5 or 6 around the world)

I can understand how the first one can be implemented, but not so much the second one. Will look into it though as it will be cleaner

**Comment by charliemaxh** [comment]
New feature added to display different cities if names are the same and allow user to select the precise one

Branch feature/location-disambiguity
